### ISSUE TITLE
lifesim_gui crashes on startup

### ISSUE THREAD

**Issue by TornadoCookie** [TornadoCookie/life-sim#2]
When starting lifesim_gui, it opens a window, then crashes with a segfault.

When running lifesim_gui with gdb:

```
Thread 1 "lifesim_gui" received signal SIGSEGV, Segmentation fault.
0x00005555555721e4 in PlayerLife::StartRandomLife (this=0x5555556e0ea0) at ../backend/life/life.cpp:62
62          loading_screen_callback(1, 5);
(gdb) bt
#0  0x00005555555721e4 in PlayerLife::StartRandomLife (this=0x5555556e0ea0) at ../backend/life/life.cpp:62
#1  0x000055555557069d in Interface::StartRandomLife (this=this@entry=0x5555556a6140) at ../backend/interface/interface.cpp:48
#2  0x000055555555e17e in main () at ../frontend/gui/main.cpp:63
```

**Comment by TornadoCookie** [comment]
Fixed by d96d30c.
