### ISSUE TITLE
Randomly crashes

### ISSUE THREAD

**Issue by TornadoCookie** [TornadoCookie/life-sim#5]
Randomly, the simulator crashes.
When run with gdb:
```
Thread 1 "lifesim_terminal" received signal SIGSEGV, Segmentation fault.
romanize_text (romanize="陽菜 關\"", nation=...) at ../backend/names/name_generator.cpp:122
122             if (!(*romanized_str)) romanized_str++;
(gdb) bt
#0  romanize_text (romanize="陽菜 關\"", nation=...) at ../backend/names/name_generator.cpp:122
#1  0x00005555555626ce in get_random_full_name_network[abi:cxx11](Nation, Gender, bool) (nation=..., gender=<optimized out>, use_unicode=<optimized out>) at ../backend/names/name_generator.cpp:209
#2  0x0000555555562fc2 in NameGenerator::get_random_full_name[abi:cxx11](Nation, Gender) (this=<optimized out>, nation=..., gender=Gender::Female) at ../backend/names/name_generator.cpp:252
#3  0x00005555555633dc in NameGenerator::GetRandomFirstName[abi:cxx11](Nation, Gender) (this=this@entry=0x55555559d030, nation=..., gender=gender@entry=Gender::Female) at ../backend/names/name_generator.cpp:300
#4  0x000055555555c806 in PlayerLife::StartRandomLife (this=0x5555555aeea0) at ../backend/life/life.cpp:63
#5  0x000055555555ac1d in Interface::StartRandomLife (this=this@entry=0x555555574140) at ../backend/interface/interface.cpp:48
#6  0x0000555555559c4f in start_over (interface=0x555555574140) at ../frontend/terminal/main.cpp:282
#7  0x00005555555574d0 in main () at ../frontend/terminal/main.cpp:323
```

**Comment by TornadoCookie** [comment]
This may be easier to fix when we implement offline mode (#1 ).
